FROM ubuntu:latest
RUN apt-get update && apt-get upgrade -y
RUN apt-get install python3.8 python3-pip -y
RUN pip3 install lime tensorflow streamlit Pillow
#COPY /Users/jeff/tmp/astro-dev/include/code/streamlit_app.py streamlit_app.py
